title:            Maxime Dénès
tagline:          Homepage of Maxime Dénès
description:      Homepage of Maxime Dénès.
canonical: http://www.maximedenes.fr

# Owner/author information
owner:
  name:           Maxime Dénès
  avatar:         avatar.png
  bio:            "Engineer"
  email:          mail@maximedenes.fr
  #  twitter:
  github:         maximedenes
  #  instagram:
  #  dribbble:
  #  disqus:
  location:       "Nice, FR"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /
  - title: Contact
    url: /contact
  - title: Github
    url: https://github.com/maximedenes
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
